// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: test.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Sub) Reset() {
	*x = Sub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub) ProtoMessage() {}

func (x *Sub) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub.ProtoReflect.Descriptor instead.
func (*Sub) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Sub) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Sub) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Z []int32 `protobuf:"zigzag32,1,rep,packed,name=z,proto3" json:"z,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *List) GetZ() []int32 {
	if x != nil {
		return x.Z
	}
	return nil
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A uint32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B uint64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C int32     `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	D int64     `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
	E int32     `protobuf:"zigzag32,5,opt,name=e,proto3" json:"e,omitempty"`
	F int64     `protobuf:"zigzag64,6,opt,name=f,proto3" json:"f,omitempty"`
	G uint32    `protobuf:"fixed32,7,opt,name=g,proto3" json:"g,omitempty"`
	H uint64    `protobuf:"fixed64,8,opt,name=h,proto3" json:"h,omitempty"`
	I float32   `protobuf:"fixed32,9,opt,name=i,proto3" json:"i,omitempty"`
	J float64   `protobuf:"fixed64,10,opt,name=j,proto3" json:"j,omitempty"`
	K []byte    `protobuf:"bytes,11,opt,name=k,proto3" json:"k,omitempty"`
	L string    `protobuf:"bytes,12,opt,name=l,proto3" json:"l,omitempty"`
	M []uint64  `protobuf:"varint,13,rep,packed,name=m,proto3" json:"m,omitempty"`
	N *Sub      `protobuf:"bytes,14,opt,name=n,proto3" json:"n,omitempty"`
	O *List     `protobuf:"bytes,15,opt,name=o,proto3" json:"o,omitempty"`
	P []int32   `protobuf:"zigzag32,16,rep,name=p,proto3" json:"p,omitempty"`
	Q []*Sub    `protobuf:"bytes,17,rep,name=q,proto3" json:"q,omitempty"`
	R uint32    `protobuf:"varint,18,opt,name=r,proto3" json:"r,omitempty"`
	S []byte    `protobuf:"bytes,19,opt,name=s,proto3" json:"s,omitempty"`
	T []float32 `protobuf:"fixed32,20,rep,packed,name=t,proto3" json:"t,omitempty"`
	U []float64 `protobuf:"fixed64,21,rep,packed,name=u,proto3" json:"u,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Test) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Test) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Test) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Test) GetD() int64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *Test) GetE() int32 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *Test) GetF() int64 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *Test) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Test) GetH() uint64 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *Test) GetI() float32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Test) GetJ() float64 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *Test) GetK() []byte {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *Test) GetL() string {
	if x != nil {
		return x.L
	}
	return ""
}

func (x *Test) GetM() []uint64 {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *Test) GetN() *Sub {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *Test) GetO() *List {
	if x != nil {
		return x.O
	}
	return nil
}

func (x *Test) GetP() []int32 {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *Test) GetQ() []*Sub {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *Test) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Test) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Test) GetT() []float32 {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Test) GetU() []float64 {
	if x != nil {
		return x.U
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x62,
	0x66, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x22,
	0x21, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x79, 0x22, 0x14, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x11, 0x52, 0x01, 0x7a, 0x22, 0xf9, 0x02, 0x0a, 0x04, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x61, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a,
	0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x01, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x01, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01,
	0x68, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x69, 0x12,
	0x0c, 0x0a, 0x01, 0x6a, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x6a, 0x12, 0x0c, 0x0a,
	0x01, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x6c,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x0d,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x01, 0x6d, 0x12, 0x24, 0x0a, 0x01, 0x6e, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x01, 0x6e, 0x12, 0x25, 0x0a,
	0x01, 0x6f, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x01, 0x6f, 0x12, 0x10, 0x0a, 0x01, 0x70, 0x18, 0x10, 0x20, 0x03, 0x28, 0x11, 0x42,
	0x02, 0x10, 0x00, 0x52, 0x01, 0x70, 0x12, 0x24, 0x0a, 0x01, 0x71, 0x18, 0x11, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18,
	0x13, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x14, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x01, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x15, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x01, 0x75, 0x42, 0x28, 0x48, 0x03, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x62, 0x66,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_proto_goTypes = []interface{}{
	(*Sub)(nil),  // 0: pbf.internal.test.Sub
	(*List)(nil), // 1: pbf.internal.test.List
	(*Test)(nil), // 2: pbf.internal.test.Test
}
var file_test_proto_depIdxs = []int32{
	0, // 0: pbf.internal.test.Test.n:type_name -> pbf.internal.test.Sub
	1, // 1: pbf.internal.test.Test.o:type_name -> pbf.internal.test.List
	0, // 2: pbf.internal.test.Test.q:type_name -> pbf.internal.test.Sub
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
